a, b = input().split()
sum = int(a) + int(b)
min = int(a) - int(b)
c = int(a) * int(b)
d = int(a) // int(b)
e = int(a) % int(b)
f = int(a) / int(b)

print(sum)
print(min)
print(c)
print(d)
print(e)
print(format(f, ".2f"))